### ISSUE TITLE
accepted cookie

### ISSUE THREAD

**Issue by gomonkey** [albertborsos/yii2-gdpr-cookie-consent#8]
If you click on the button "got it" this have not to save the cookies.

Suppose i am in option and I change the defaults value and then I click on save.
In second time I click on got it, because I want to close the banner, this will reset all cookie to default.

In my opinion have just to close the banner and nothing else

**Comment by albertborsos** [comment]
Yes, the toolbar will override the values which are configured from the form. Because the visitors have the right to modify their earlier decision, and this is the simplest method to change it.

I do not think there should be an option to just close the popup.  You have to choose that you accept or decline the cookie policy on the site. Also in the [cookie consent widget](https://cookieconsent.insites.com/download/) there is no support for close button.

**Comment by Raven0us** [comment]
After a user interacts with the personalization page (switches something on/off on `cookie/settings`), the **Deny** and **Allow** buttons seem not to do anything at all, it no longer "overrides" anything, as stated in this thread. Is this behaviour intended?

**Comment by albertborsos** [comment]
@Raven0us can you show me an example? I tried it on my site, and it works as expected.

**Comment by Raven0us** [comment]
@albertborsos, you are right, it works correctly on your site. I'll have a look at it myself. Thanks.

**Comment by Raven0us** [comment]
@albertborsos, I've had a look and created an issue at https://github.com/albertborsos/yii2-gdpr-cookie-consent/issues/14
